import 'bus_route.dart';

final List<BusRoute> duBusRoutes = [
  BusRoute(
    id: 'kinchit', nameEn: 'Kinchit', nameBn: 'কিঞ্চিৎ',
    fbGroup: 'https://www.facebook.com/groups/136030586418416',
    stops: ['DU Campus', 'Old Ramna Thana', 'Mogbazar', 'Wireless', 'Mouchak (Malibagh)', 'Malibag Mor', 'Razarbag Mor', 'Pir Jongi Mazar', 'Kamlapur', 'Arambagh'],
    schedule: [
      BusTrip(time: '07:00 AM', busNo: '5919', type: 'up'),
      BusTrip(time: '08:00 AM', busNo: '5919', type: 'up'),
      BusTrip(time: '08:50 AM', busNo: '6268', type: 'up'),
      BusTrip(time: '09:50 AM', busNo: '6042', type: 'up'),
      BusTrip(time: '12:30 PM', busNo: '5847', type: 'down'),
      BusTrip(time: '01:30 PM', busNo: '6116', type: 'down'),
      BusTrip(time: '02:30 PM', busNo: '6054', type: 'down'),
      BusTrip(time: '03:20 PM', busNo: '6042', type: 'down'),
      BusTrip(time: '04:20 PM', busNo: '5919', type: 'down'),
      BusTrip(time: '05:30 PM', busNo: '6042', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'choitaly', nameEn: 'Choitaly', nameBn: 'চৈতালী',
    fbGroup: 'https://www.facebook.com/groups/3616259282018054',
    stops: ['DU Campus', 'Shaymoli', 'Kallyanpur', 'Bangla College', 'Ansar Camp', 'Chinese', 'Mirpur-01', 'Mirpur-02', 'Prashika', 'Rabbani Hotel', 'Setara Convention Hall', 'Chourangi'],
    schedule: [
      BusTrip(time: '06:40 AM', busNo: '6254', type: 'up'),
      BusTrip(time: '07:10 AM', busNo: '6292', type: 'up'),
      BusTrip(time: '07:10 AM', busNo: '6124', type: 'up'),
      BusTrip(time: '07:50 AM', busNo: '7303', type: 'up'),
      BusTrip(time: '09:00 AM', busNo: '6199', type: 'up'),
      BusTrip(time: '09:00 AM', busNo: '5793', type: 'up'),
      BusTrip(time: '10:00 AM', busNo: '6260', type: 'up'),
      BusTrip(time: '10:00 AM', busNo: '6104', type: 'up'),
      BusTrip(time: '12:20 PM', busNo: '6254', type: 'down'),
      BusTrip(time: '01:30 PM', busNo: '6124', type: 'down'),
      BusTrip(time: '02:30 PM', busNo: '6199', type: 'down'),
      BusTrip(time: '03:30 PM', busNo: '5793', type: 'down'),
      BusTrip(time: '04:10 PM', busNo: '6292', type: 'down'),
      BusTrip(time: '05:10 PM', busNo: '7303', type: 'down'),
      BusTrip(time: '05:50 PM', busNo: '6260', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'srabon', nameEn: 'Shrabon', nameBn: 'শ্রাবণ',
    fbGroup: 'https://www.facebook.com/groups/srabon.mugdapara/',
    stops: ['DU Campus', 'Golapbagh', 'Maniknagar', 'Mugda Stadium', 'Mugda Garments', 'Mugda Bishwaroad', 'Mugda Medical', 'Buddha Mondir', 'Basabo', 'Khilgaon Railgate'],
    schedule: [
      BusTrip(time: '07:00 AM', busNo: '', type: 'up'),
      BusTrip(time: '07:20 AM', busNo: '', type: 'up'),
      BusTrip(time: '07:55 AM', busNo: '', type: 'up'),
      BusTrip(time: '08:15 AM', busNo: '', type: 'up'),
      BusTrip(time: '09:00 AM', busNo: '', type: 'up'),
      BusTrip(time: '10:00 AM', busNo: '', type: 'up'),
      BusTrip(time: '12:15 PM', busNo: '', type: 'down'),
      BusTrip(time: '01:30 PM', busNo: '', type: 'down'),
      BusTrip(time: '02:20 PM', busNo: '', type: 'down'),
      BusTrip(time: '03:40 PM', busNo: '', type: 'down'),
      BusTrip(time: '04:30 PM', busNo: '', type: 'down'),
      BusTrip(time: '05:00 PM', busNo: '', type: 'down'),
      BusTrip(time: '05:30 PM', busNo: '', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'taranga', nameEn: 'Taranga', nameBn: 'তরঙ্গ',
    fbGroup: 'https://www.facebook.com/groups/taranga.bus/',
    stops: ['DU Campus', 'Jigatola', 'Dhanmondi-15', 'Star Kabab', 'Shankar', 'Graphics Institute', 'Mohammadpur Bus Stand', 'Salimullah Road', 'Town Hall', 'Post Office', 'Asad Gate'],
    schedule: [
      BusTrip(time: '07:10 AM', busNo: '6088', type: 'up'),
      BusTrip(time: '07:30 AM', busNo: '5708', type: 'up'),
      BusTrip(time: '08:00 AM', busNo: '6137', type: 'up'),
      BusTrip(time: '08:30 AM', busNo: '6254', type: 'up'),
      BusTrip(time: '09:10 AM', busNo: '6088', type: 'up'),
      BusTrip(time: '09:45 AM', busNo: '6230', type: 'up'),
      BusTrip(time: '10:15 AM', busNo: '5708', type: 'up'),
      BusTrip(time: '12:30 PM', busNo: '5044', type: 'down'),
      BusTrip(time: '01:15 PM', busNo: '6088', type: 'down'),
      BusTrip(time: '02:00 PM', busNo: '6137', type: 'down'),
      BusTrip(time: '03:00 PM', busNo: '6230', type: 'down'),
      BusTrip(time: '03:30 PM', busNo: '6071', type: 'down'),
      BusTrip(time: '04:15 PM', busNo: '6088', type: 'down'),
      BusTrip(time: '04:45 PM', busNo: '5708', type: 'down'),
      BusTrip(time: '05:15 PM', busNo: '6137', type: 'down'),
      BusTrip(time: '05:30 PM', busNo: '6254', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'basanta', nameEn: 'Basanta', nameBn: 'বসন্ত',
    fbGroup: 'https://www.facebook.com/groups/basanta.du/',
    stops: ['DU Campus', 'Rampura TV Center', 'Rampura Bazar', 'Hazipara Petrol Pump', 'Malibag Community Center', 'Khilgaon Police Fari'],
    schedule: [
      BusTrip(time: '07:00 AM', busNo: '5821', type: 'up'),
      BusTrip(time: '07:40 AM', busNo: '6071', type: 'up'),
      BusTrip(time: '08:20 AM', busNo: '6116', type: 'up'),
      BusTrip(time: '09:00 AM', busNo: '5850', type: 'up'),
      BusTrip(time: '10:00 AM', busNo: '5821', type: 'up'),
      BusTrip(time: '12:35 PM', busNo: '5992', type: 'down'),
      BusTrip(time: '01:35 PM', busNo: '7303', type: 'down'),
      BusTrip(time: '02:35 PM', busNo: '6104', type: 'down'),
      BusTrip(time: '03:35 PM', busNo: '5821', type: 'down'),
      BusTrip(time: '04:35 PM', busNo: '6115', type: 'down'),
      BusTrip(time: '05:35 PM', busNo: '5817', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'boishakhi', nameEn: 'Boishakhi', nameBn: 'বৈশাখী',
    fbGroup: 'https://www.facebook.com/groups/baishakhi/',
    stops: ['DU Campus', 'Second Gate', 'Taltola', 'Shwerapara', 'Kazipara', 'Mirpur-10','Water Tank', 'Police Staff College','Mirpur-14'],
    schedule: [
      BusTrip(time: '06:40 AM', busNo: '5900', type: 'up'),
      BusTrip(time: '07:00 AM', busNo: '5817', type: 'up'),
      BusTrip(time: '07:30 AM', busNo: '5867', type: 'up'),
      BusTrip(time: '08:00 AM', busNo: '6231', type: 'up'),
      BusTrip(time: '08:45 AM', busNo: '6204', type: 'up'),
      BusTrip(time: '09:25 AM', busNo: '6264', type: 'up'),
      BusTrip(time: '10:00 AM', busNo: '5900', type: 'up'),
      BusTrip(time: '12:30 PM', busNo: '6231', type: 'down'),
      BusTrip(time: '01:15 PM', busNo: '5817', type: 'down'),
      BusTrip(time: '02:20 PM', busNo: '5900', type: 'down'),
      BusTrip(time: '03:30 PM', busNo: '6204', type: 'down'),
      BusTrip(time: '04:15 PM', busNo: '5866', type: 'down'),
      BusTrip(time: '04:45 PM', busNo: '6264', type: 'down'),
      BusTrip(time: '05:30 PM', busNo: '6231', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'khonika', nameEn: 'Khonika', nameBn: 'ক্ষণিকা',
    fbGroup: 'https://www.facebook.com/groups/136899656480809/',
    stops: ['DU Campus', 'Kuril Bishwaroad', 'Khilkhet', 'Kurmitola', 'Kawla', 'Airport', 'Jashimuddin', 'Azompur', 'House Building', 'Abdullahpur', 'Station Road', 'College Gate', 'Gazipura', 'Borobari', 'Boardbazar', 'Signboard (Gazipur)', 'Bypass', 'Chowrasta', 'Shib Bari'],
    schedule: [
      BusTrip(time: '06:00 AM', busNo: '6213', type: 'up'),
      BusTrip(time: '06:20 AM', busNo: '6262', type: 'up'),
      BusTrip(time: '06:40 AM', busNo: '5731', type: 'up'),
      BusTrip(time: '06:40 AM', busNo: '5709', type: 'up'),
      BusTrip(time: '07:00 AM', busNo: '5724', type: 'up'),
      BusTrip(time: '07:30 AM', busNo: '5849', type: 'up'),
      BusTrip(time: '08:00 AM', busNo: '6249', type: 'up'),
      BusTrip(time: '08:15 AM', busNo: '6824', type: 'up'),
      BusTrip(time: '09:00 AM', busNo: '6230', type: 'up'),
      BusTrip(time: '12:15 PM', busNo: '6262', type: 'down'),
      BusTrip(time: '01:10 PM', busNo: '5709', type: 'down'),
      BusTrip(time: '01:45 PM', busNo: '6213', type: 'down'),
      BusTrip(time: '02:30 PM', busNo: '5724', type: 'down'),
      BusTrip(time: '03:10 PM', busNo: '6230', type: 'down'),
      BusTrip(time: '03:50 PM', busNo: '5731', type: 'down'),
      BusTrip(time: '04:30 PM', busNo: '5849', type: 'down'),
      BusTrip(time: '05:10 PM', busNo: '6249', type: 'down'),
      BusTrip(time: '05:40 PM', busNo: '6824', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'hemonto', nameEn: 'Hemonto', nameBn: 'হেমন্ত',
    fbGroup: 'https://www.facebook.com/groups/hemontofamily/',
    stops: ['DU Campus', 'Nabinagar (Savar)', '20 Mile', 'Prantik', 'Jahangirnagar', 'C & B', 'Radio Colony', 'C R P', 'Pakiza', 'Genda', 'Bank Town', 'Police Town', 'Hemayetpur', 'Alomnagar', 'Aminbazar'],
    schedule: [
      BusTrip(time: '06:10 AM', busNo: '6028', type: 'up'),
      BusTrip(time: '06:50 AM', busNo: '6130', type: 'up'),
      BusTrip(time: '07:30 AM', busNo: '6216', type: 'up'),
      BusTrip(time: '08:30 AM', busNo: '6205', type: 'up'),
      BusTrip(time: '01:10 PM', busNo: '6216', type: 'down'),
      BusTrip(time: '03:30 PM', busNo: '6205', type: 'down'),
      BusTrip(time: '05:10 PM', busNo: '6130', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'ullash', nameEn: 'Ullash', nameBn: 'উল্লাস',
    fbGroup: 'https://www.facebook.com/groups/ullashdu123/',
    stops: ['DU Campus', 'Tikatuli Flyover', 'Dholaipar', 'Postogola', 'Jurain', 'Nabinagar (Jatrabari)', 'Mirhajari Bagh', 'Dayaganj'],
    schedule: [
      BusTrip(time: '07:00 AM', busNo: '', type: 'up'),
      BusTrip(time: '08:00 AM', busNo: '', type: 'up'),
      BusTrip(time: '08:30 AM', busNo: '', type: 'up'),
      BusTrip(time: '09:00 AM', busNo: '', type: 'up'),
      BusTrip(time: '09:30 AM', busNo: '', type: 'up'),
      BusTrip(time: '10:00 AM', busNo: '', type: 'up'),
      BusTrip(time: '12:10 PM', busNo: '', type: 'down'),
      BusTrip(time: '01:10 PM', busNo: '', type: 'down'),
      BusTrip(time: '02:10 PM', busNo: '', type: 'down'),
      BusTrip(time: '03:10 PM', busNo: '', type: 'down'),
      BusTrip(time: '04:15 PM', busNo: '', type: 'down'),
      BusTrip(time: '05:10 PM', busNo: '', type: 'down'),
      BusTrip(time: '05:35 PM', busNo: '', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'falguni', nameEn: 'Falguni', nameBn: 'ফাল্গুনী',
    fbGroup: 'https://www.facebook.com/groups/149830555087741/',
    stops: ['DU Campus', 'Nabisco', 'Mohakhali', 'Wireless', 'TB Gate', 'Gulshan-1', 'Gudaraghat', 'Middle Badda', 'Hossain Market', 'Uttar Badda', 'Suabastu Tower', 'Shahzadpur', 'Bashtola', 'Notun Bazar'],
    schedule: [
      BusTrip(time: '06:40 AM', busNo: '6051', type: 'up'),
      BusTrip(time: '07:40 AM', busNo: '6139', type: 'up'),
      BusTrip(time: '08:40 AM', busNo: '6051', type: 'up'),
      BusTrip(time: '01:10 PM', busNo: '6239', type: 'down'),
      BusTrip(time: '02:30 PM', busNo: '5916', type: 'down'),
      BusTrip(time: '04:10 PM', busNo: '6051', type: 'down'),
      BusTrip(time: '05:10 PM', busNo: '6139', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'ishakha', nameEn: 'Isha Kha', nameBn: 'ঈশা খাঁ',
    fbGroup: 'https://www.facebook.com/groups/ishakha/',
    stops: ['DU Campus', 'Kazla', 'Shonir Akhra', 'Rayerbag', 'Matuail', 'Madrasah Road', 'Signboard (Narayanganj)', 'Shanarpar', 'Mouchak (Siddhirganj)', '10Tola', 'Chittagong Road', 'Kachpur Bridge', 'Madanpur', 'Langolbondo', 'Mograpara'],
    schedule: [
      BusTrip(time: '06:40 AM', busNo: '', type: 'up', busType: 'Single Decker'),
      BusTrip(time: '06:50 AM', busNo: '', type: 'up', busType: 'Double Decker'),
      BusTrip(time: '07:25 AM', busNo: '', type: 'up', busType: 'Staff'),
      BusTrip(time: '07:30 AM', busNo: '', type: 'up', busType: 'Double Decker'),
      BusTrip(time: '07:45 AM', busNo: '', type: 'up', busType: 'Staff'),
      BusTrip(time: '08:20 AM', busNo: '', type: 'up', busType: 'Single Decker'),
      BusTrip(time: '08:45 AM', busNo: '', type: 'up', busType: 'Double Decker'),
      BusTrip(time: '09:00 AM', busNo: '', type: 'up', busType: 'Single Decker'),
      BusTrip(time: '09:30 AM', busNo: '', type: 'up', busType: 'Single Decker'),
      BusTrip(time: '10:00 AM', busNo: '', type: 'up', busType: 'Single Decker'),
      BusTrip(time: '12:20 PM', busNo: '', type: 'down', busType: 'Single Decker'),
      BusTrip(time: '01:30 PM', busNo: '', type: 'down', busType: 'Single Decker'),
      BusTrip(time: '01:30 PM', busNo: '', type: 'down', busType: 'Double Decker'),
      BusTrip(time: '02:30 PM', busNo: '', type: 'down', busType: 'Double Decker'),
      BusTrip(time: '03:30 PM', busNo: '', type: 'down', busType: 'Single Decker'),
      BusTrip(time: '04:10 PM', busNo: '', type: 'down', busType: 'Double Decker'),
      BusTrip(time: '04:40 PM', busNo: '', type: 'down', busType: 'Single Decker'),
      BusTrip(time: '05:05 PM', busNo: '', type: 'down', busType: 'Staff'),
      BusTrip(time: '05:40 PM', busNo: '', type: 'down', busType: 'Double Decker'),
    ],
  ),
  BusRoute(
    id: 'maitree', nameEn: 'Maitree', nameBn: 'মৈত্রী',
    fbGroup: 'https://www.facebook.com/groups/195330720589845/',
    stops: ['DU Campus', 'Kazla', 'Jatrabari', 'Vangapress', 'Mridhabari', 'Council', 'Kather Pool', 'Konapara', 'Basher Pool', 'Bamoyil', 'Staff Quarter', 'Sarulia', 'Ranimahal', 'Golakata', 'Chittagong Road', 'Siddhirganj Pool', 'Power House', 'Adamji', '2no. Dhakeshwari', 'Chowdhury Bari', 'IIT School'],
    schedule: [
      BusTrip(time: '06:15 AM', busNo: '', type: 'up'),
      BusTrip(time: '07:10 AM', busNo: '', type: 'up'),
      BusTrip(time: '07:45 AM', busNo: '', type: 'up'),
      BusTrip(time: '08:20 AM', busNo: '', type: 'up'),
      BusTrip(time: '09:15 AM', busNo: '', type: 'up'),
      BusTrip(time: '12:15 PM', busNo: '', type: 'down'),
      BusTrip(time: '01:15 PM', busNo: '', type: 'down'),
      BusTrip(time: '02:15 PM', busNo: '', type: 'down'),
      BusTrip(time: '03:15 PM', busNo: '', type: 'down'),
      BusTrip(time: '05:05 PM', busNo: '', type: 'down'),
      BusTrip(time: '05:15 PM', busNo: '', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'wari_bateshwar', nameEn: 'Wari-Bateshwar', nameBn: 'উয়ারী-বটেশ্বর',
    fbGroup: 'https://www.facebook.com/groups/211108485928248/',
    stops: ['DU Campus', 'Borab', 'Ruposhi', 'Boropa', 'Gauchia', 'Purinda', 'Madhabdi', 'Shah-e-Protab', 'Pachdona', 'Velanagar', 'Itakhola', 'Shrishtigarh', 'Chaitannyo', 'Morjal', 'Baroicha (Narshighdi)'],
    schedule: [
      BusTrip(time: '06:20 AM', busNo: '112350', type: 'up'),
      BusTrip(time: '06:30 AM', busNo: '', type: 'up'),
      BusTrip(time: '02:00 PM', busNo: '112350', type: 'down'),
      BusTrip(time: '04:45 PM', busNo: '', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'idrakpur', nameEn: 'Idrakpur', nameBn: 'ইদ্রাকপুর',
    fbGroup: 'https://www.facebook.com/groups/idrakpur.du/',
    stops: ['DU Campus', 'Signboard (Narayanganj)', 'Jalkuri', 'Vuighor', 'Osman Ali Stadium', 'Shibu Market', 'Jela Parishad', 'Chashara', '2nd Gate', 'Mondolpara'],
    schedule: [
      BusTrip(time: '06:35 AM', busNo: '', type: 'up'),
      BusTrip(time: '03:10 PM', busNo: '', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'bikrampur', nameEn: 'Bikrampur', nameBn: 'বিক্রমপুর',
    fbGroup: 'https://www.facebook.com/groups/bikrampurdu/',
    stops: ['DU Campus', 'Babubazar', 'Razendrapur', 'Nimtoli', 'Srinagar Ferry Ghat', 'Mawa Ghat'],
    schedule: [
      BusTrip(time: '07:00 AM', busNo: '5900', type: 'up'),
      BusTrip(time: '04:10 PM', busNo: '6231', type: 'down'),
    ],
  ),
  BusRoute(
    id: 'ananda', nameEn: 'Ananda', nameBn: 'আনন্দ',
    fbGroup: 'https://www.facebook.com/groups/ananda.du',
    stops: ['DU Campus', 'Signboard (Narayanganj)', 'Vuighor', 'Jalkuri', 'Osman Ali Stadium', 'Shibu Market', 'Chashara', 'Jela Parishad', '2nd Gate', 'Mondolpara'],
    schedule: [
      BusTrip(time: '06:50 AM', busNo: '', type: 'up'),
      BusTrip(time: '07:40 AM', busNo: '', type: 'up'),
      BusTrip(time: '08:40 AM', busNo: '', type: 'up'),
      BusTrip(time: '09:50 AM', busNo: '', type: 'up'),
      BusTrip(time: '01:10 PM', busNo: '', type: 'down'),
      BusTrip(time: '02:30 PM', busNo: '', type: 'down'),
      BusTrip(time: '04:10 PM', busNo: '', type: 'down'),
      BusTrip(time: '05:15 PM', busNo: '', type: 'down'),
    ],
  ),
];
